name = "Modpack Calderoh"
author = "CarlosM"
version = "1.2.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14176ab11c504cb66c0cb3acba51254e5550e3725bef90db39883694e466bfa7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
